import React, { createContext, useState, useEffect, useContext, ReactNode, useCallback } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Définition du type de traduction
type TranslationMap = { [key: string]: string };

// Définition des traductions
const translations: { [lang: string]: TranslationMap } = {
  fr: {
    // Général
    'Accueil': 'Accueil',
    'Paramètres': 'Paramètres',
    'Déconnexion': 'Déconnexion',
    'Annuler': 'Annuler',
    'Sauvegarder': 'Sauvegarder',
    'Erreur': 'Erreur',
    'Succès': 'Succès',
    'Chargement...': 'Chargement...',
    'Non renseigné': 'Non renseigné',
    'Voir tout': 'Voir tout',

    // Paramètres
    'Préférences': 'Préférences',
    'Langue': 'Langue',
    'Mode sombre': 'Mode sombre',
    'Activer le thème sombre': 'Activer le thème sombre',
    'Synchronisation auto': 'Synchronisation auto',
    'Synchroniser automatiquement les données': 'Synchroniser automatiquement les données',
    'Notifications': 'Notifications',
    'Notifications Push': 'Notifications Push',
    'Recevoir des notifications en temps réel': 'Recevoir des notifications en temps réel',
    'Notifications par email': 'Notifications par e-mail',
    'Recevoir des résumés par email': 'Recevoir des résumés par e-mail',
    'Envoyer notification test': 'Envoyer notification test',
    'Envoyer une notification pour tester': 'Envoyer une notification pour tester',
    'Sécurité': 'Sécurité',
    'Authentification biométrique': 'Authentification biométrique',
    'Utiliser Face ID / Touch ID': 'Utiliser Face ID / Touch ID',
    'Changer le mot de passe': 'Changer le mot de passe',
    'Modifier votre mot de passe': 'Modifier votre mot de passe',
    'Sessions actives': 'Sessions actives',
    'Gérer vos sessions connectées': 'Gérer vos sessions connectées',
    'Compte': 'Compte',
    'Informations personnelles': 'Informations personnelles',
    'Modifier votre profil': 'Modifier votre profil',
    'Confidentialité': 'Confidentialité',
    'Paramètres de confidentialité': 'Paramètres de confidentialité',
    'Exporter mes données': 'Exporter mes données',
    'Télécharger vos données': 'Télécharger vos données',
    'Support': 'Support',
    'Centre d\'aide': 'Centre d\'aide',
    'FAQ et guides d\'utilisation': 'FAQ et guides d\'utilisation',
    'Nous contacter': 'Nous contacter',
    'Obtenir de l\'aide': 'Obtenir de l\'aide',
    'À propos': 'À propos',
    'Informations sur l\'application': 'Informations sur l\'application',
    'Se déconnecter': 'Se déconnecter',
    'Déconnexion...': 'Déconnexion...',
    'Confirmation': 'Confirmation',
    'Êtes-vous sûr de vouloir vous déconnecter ?': 'Êtes-vous sûr de vouloir vous déconnecter ?',

    // Candidatures
    'Mes Candidatures': 'Mes Candidatures',
    'Toutes mes candidatures': 'Toutes mes candidatures',
    'En attente': 'En attente',
    'Acceptée': 'Acceptée',
    'Refusée': 'Refusée',
    'Aucune candidature': 'Aucune candidature',
    'Vos candidatures apparaîtront ici': 'Vos candidatures apparaîtront ici',
    'Chargement de vos candidatures...': 'Chargement de vos candidatures...',
    'Impossible de charger vos candidatures.': 'Impossible de charger vos candidatures.',
    'Retour': 'Retour',
    'Retour aux candidatures': 'Retour aux candidatures',
    'Candidature introuvable': 'Candidature introuvable',
    'Cette candidature n\'existe plus ou n\'est pas accessible.': 'Cette candidature n\'existe plus ou n\'est pas accessible.',
    'Postulé le:': 'Postulé le:',
    'Détails Candidature': 'Détails Candidature',
    'Statut de la candidature': 'Statut de la candidature',
    'Offre d\'emploi': 'Offre d\'emploi',
    'Lieu': 'Lieu',
    'Contrat': 'Contrat',
    'Salaire': 'Salaire',
    'Expérience': 'Expérience',
    'Niveau': 'Niveau',
    'Domaine': 'Domaine',
    'Lettre de motivation': 'Lettre de motivation',
    'Non spécifié': 'Non spécifié',
    'Non disponible': 'Non disponible',
    'N/A': 'N/A',
    'an(s)': 'an(s)',

    // Actualités
    'Actualités': 'Actualités',
    'Toutes les Actualités': 'Toutes les Actualités',
    'Dernières Actualités': 'Dernières Actualités',
    'Chargement des actualités...': 'Chargement des actualités...',
    'Impossible de charger les actualités.': 'Impossible de charger les actualités.',
    'Aucune actualité disponible pour le moment.': 'Aucune actualité disponible pour le moment.',
    'Publié le:': 'Publié le:',
    'Vues:': 'Vues:',
    'Catégorie:': 'Catégorie:',
    'Description non disponible.': 'Description non disponible.',
    'Détails Actualité': 'Détails Actualité',

    // CV & Profil Candidat
    'Mon Profil': 'Mon Profil',
    'Mon CV & Candidat': 'Mon CV & Candidat',
    'Mes informations personnelles': 'Mes informations personnelles',
    'Nom complet': 'Nom complet',
    'Email': 'E-mail',
    'Téléphone': 'Téléphone',
    'Nom': 'Nom',
    'Modifier ces informations': 'Modifier ces informations',
    'Nom complet CV': 'Nom complet CV',
    'Email CV': 'E-mail CV',
    'Téléphone CV': 'Téléphone CV',
    'Résumé': 'Résumé',
    'Résumé professionnel': 'Résumé professionnel',
    'Décrivez votre profil professionnel...': 'Décrivez votre profil professionnel...',
    'Compétences': 'Compétences',
    'Ajouter une compétence': 'Ajouter une compétence',
    'Expérience Professionnelle': 'Expérience Professionnelle',
    'Poste': 'Poste',
    'Entreprise': 'Entreprise',
    'Période': 'Période',
    'Lieu de travail': 'Lieu de travail',
    'Description': 'Description',
    'Formation': 'Formation',
    'Nom de l\'établissement/diplôme': 'Nom de l\'établissement/diplôme',
    'Supprimer': 'Supprimer',
    'Ajouter une expérience': 'Ajouter une expérience',
    'Ajouter une formation': 'Ajouter une formation',
    'Télécharger/Mettre à jour le CV': 'Télécharger/Mettre à jour le CV',
    'Mes informations de CV': 'Mes informations de CV',
    'Chargement des données...': 'Chargement des données...',
    'Aucune donnée CV': 'Aucune donnée CV',
    'Saisissez manuellement vos informations ou téléchargez un CV.': 'Saisissez manuellement vos informations ou téléchargez un CV.',
    'Modifier les données du CV': 'Modifier les données du CV',
    'Saisir les données du CV': 'Saisir les données du CV',
    'Exporter le CV (PDF)': 'Exporter le CV (PDF)',
    'Exportation...': 'Exportation...',
    'Impossible d\'exporter le CV.': 'Impossible d\'exporter le CV.',
    'Aucune donnée de CV à exporter.': 'Aucune donnée de CV à exporter.',
    'Titre de profil': 'Titre de profil',
    'Disponibilité': 'Disponibilité',
    'Statut': 'Statut',
    'En Écoute': 'En Écoute',
    'Indisponible': 'Indisponible',
    'Pas de profil candidat': 'Pas de profil candidat',
    'Créez votre profil candidat pour postuler à des offres.': 'Créez votre profil candidat pour postuler à des offres.',
    'Créer mon profil candidat': 'Créer mon profil candidat',
    'Statut (1: En Écoute, 0: Indisponible)': 'Statut (1: En Écoute, 0: Indisponible)',

    // Authentification et sécurité
    'Configurer l\'authentification biométrique': 'Configurer l\'authentification biométrique',
    'Souhaitez-vous configurer l\'authentification biométrique avec ces identifiants ?': 'Souhaitez-vous configurer l\'authentification biométrique avec ces identifiants ?',
    'Authentification biométrique configurée avec succès !': 'Authentification biométrique configurée avec succès !',
    'Échec de la configuration de l\'authentification biométrique.': 'Échec de la configuration de l\'authentification biométrique.',
    'Erreur lors de la configuration.': 'Erreur lors de la configuration.',
    'Connectez-vous d\'abord avec votre email et mot de passe pour activer la connexion biométrique.': 'Connectez-vous d\'abord avec votre email et mot de passe pour activer la connexion biométrique.',
    'Saisissez vos identifiants puis appuyez sur ce bouton pour configurer l\'authentification biométrique.': 'Saisissez vos identifiants puis appuyez sur ce bouton pour configurer l\'authentification biométrique.',
    'Configurez l\'authentification biométrique en appuyant sur "Configurer".': 'Configurez l\'authentification biométrique en appuyant sur "Configurer".',

    // Alertes et messages d'erreur
    'Veuillez saisir le code OTP et assurez-vous que l\'email est valide.': 'Veuillez saisir le code OTP et assurez-vous que l\'email est valide.',
    'Email manquant pour le renvoi d\'OTP.': 'Email manquant pour le renvoi d\'OTP.',
    'Lien invalide': 'Lien invalide',
    'Le lien de réinitialisation est invalide. Veuillez demander un nouveau lien.': 'Le lien de réinitialisation est invalide. Veuillez demander un nouveau lien.',
    'Mot de passe réinitialisé': 'Mot de passe réinitialisé',
    'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter.': 'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter.',
    'Une erreur s\'est produite. Redirection vers la connexion...': 'Une erreur s\'est produite. Redirection vers la connexion...',

    // Espaces intérimaires et RH
    'Mon Dossier RH': 'Mon Dossier RH',
    'Prestations IPM': 'Prestations IPM',
    'Structures de soins': 'Structures de soins',
    'Détails de la structure': 'Détails de la structure',
    'Rapports': 'Rapports',
    'Graphiques détaillés': 'Graphiques détaillés',
    'Carte IPM': 'Carte IPM',
    'Analytics': 'Analytics',
    'Entretiens vidéo': 'Entretiens vidéo',
    'Entretien vidéo': 'Entretien vidéo',
    'Mes Favoris': 'Mes Favoris',

    // Messages d'erreur spécifiques
    'Veuillez sélectionner un contrat.': 'Veuillez sélectionner un contrat.',
    'Veuillez écrire votre message.': 'Veuillez écrire votre message.',
    'Votre demande d\'attestation a été envoyée avec succès.': 'Votre demande d\'attestation a été envoyée avec succès.',
    'Attestation téléchargée avec succès !': 'Attestation téléchargée avec succès !',
    'Échec du téléchargement de l\'attestation.': 'Échec du téléchargement de l\'attestation.',
    'Impossible de télécharger l\'attestation.': 'Impossible de télécharger l\'attestation.',
    'Certificat téléchargé avec succès !': 'Certificat téléchargé avec succès !',
    'Échec du téléchargement du certificat.': 'Échec du téléchargement du certificat.',
    'Impossible de télécharger le certificat.': 'Impossible de télécharger le certificat.',

    // Géolocalisation
    'Géolocalisation indisponible': 'Géolocalisation indisponible',
    'Pour une meilleure expérience, activez la géolocalisation pour trouver les structures les plus proches.': 'Pour une meilleure expérience, activez la géolocalisation pour trouver les structures les plus proches.',
    'Impossible de charger les structures': 'Impossible de charger les structures',
    'Position indisponible': 'Position indisponible',
    'Impossible de calculer l\'itinéraire sans votre position': 'Impossible de calculer l\'itinéraire sans votre position',

    // Cartes et données sensibles
    'Impossible de charger les informations de la carte': 'Impossible de charger les informations de la carte',
    'Carte verrouillée': 'Carte verrouillée',
    'Vous devez d\'abord déverrouiller la carte pour voir les données sensibles.': 'Vous devez d\'abord déverrouiller la carte pour voir les données sensibles.',
    'Carte déverrouillée': 'Carte déverrouillée',
    'Votre carte IPM est maintenant accessible.': 'Votre carte IPM est maintenant accessible.',
    'Votre carte IPM est maintenant sécurisée.': 'Votre carte IPM est maintenant sécurisée.',
    'Données masquées': 'Données masquées',
    'Les données sensibles ont été masquées.': 'Les données sensibles ont été masquées.',

    // Rapports et analyses
    'Information': 'Information',
    'Aucun rapport disponible pour le moment.': 'Aucun rapport disponible pour le moment.',
    'Impossible de charger l\'historique des rapports. Vérifiez votre connexion.': 'Impossible de charger l\'historique des rapports. Vérifiez votre connexion.',
    '✅ Rapport généré': '✅ Rapport généré',
    'Votre rapport a été généré avec succès et est maintenant disponible dans l\'historique.': 'Votre rapport a été généré avec succès et est maintenant disponible dans l\'historique.',
    '⚠️ Erreur': '⚠️ Erreur',
    'Impossible de générer le rapport. Veuillez réessayer.': 'Impossible de générer le rapport. Veuillez réessayer.',
    'Impossible de générer le rapport. Vérifiez votre connexion et réessayez.': 'Impossible de générer le rapport. Vérifiez votre connexion et réessayez.',
    '✅ Succès': '✅ Succès',
    'Rapport téléchargé et ouvert avec succès !': 'Rapport téléchargé et ouvert avec succès !',
    'Rapport sauvegardé dans': 'Rapport sauvegardé dans',
    'Impossible de télécharger le rapport. Veuillez réessayer.': 'Impossible de télécharger le rapport. Veuillez réessayer.',

    // Analyses et données
    'Impossible de charger certaines données d\'analyse. Veuillez réessayer.': 'Impossible de charger certaines données d\'analyse. Veuillez réessayer.',
    'OK': 'OK',

    // Boutons et actions
    'Plus tard': 'Plus tard',
    'Configurer': 'Configurer',
    'Compris': 'Compris',

    // Notifications
    'Notifications activées !': 'Notifications activées !',
    'Appareil physique requis': 'Appareil physique requis',
    'Les notifications Push ne fonctionnent que sur les appareils physiques ou les émulateurs configurés pour Google Play Services !': 'Les notifications Push ne fonctionnent que sur les appareils physiques ou les émulateurs configurés pour Google Play Services !',
    'Permission refusée': 'Permission refusée',
    'Impossible d\'obtenir le push token pour la notification ! Vous pouvez l\'activer dans les paramètres de votre appareil.': 'Impossible d\'obtenir le push token pour la notification ! Vous pouvez l\'activer dans les paramètres de votre appareil.',
    'Impossible d\'activer les notifications. ': 'Impossible d\'activer les notifications. ',
    'Veuillez réessayer.': 'Veuillez réessayer.',
    'Notifications désactivées': 'Notifications désactivées',
    'Les notifications ont été désactivées.': 'Les notifications ont été désactivées.',

    // Configuration biométrique avancée
    'Configuration de l\'authentification biométrique': 'Configuration de l\'authentification biométrique',
    'Pour configurer l\'authentification biométrique, veuillez saisir vos identifiants actuels.': 'Pour configurer l\'authentification biométrique, veuillez saisir vos identifiants actuels.',
    'Configuration biométrique': 'Configuration biométrique',
    'Saisissez vos identifiants pour configurer l\'authentification biométrique': 'Saisissez vos identifiants pour configurer l\'authentification biométrique',
    'Votre email': 'Votre email',
    'Votre mot de passe': 'Votre mot de passe',
    'Mot de passe': 'Mot de passe',
    'Veuillez saisir votre email et mot de passe': 'Veuillez saisir votre email et mot de passe',

    // États et statuts
    'Non disponible sur cet appareil': 'Non disponible sur cet appareil',
    'Configuré et prêt à utiliser': 'Configuré et prêt à utiliser',
    'Activé - Credentials requis': 'Activé - Credentials requis',

    // Textes divers manquants
    'Actualiser': 'Actualiser',
    'Rechercher': 'Rechercher',
    'Filtrer': 'Filtrer',
    'Trier': 'Trier',
    'Tout effacer': 'Tout effacer',
    'Aucun résultat': 'Aucun résultat',
    // Removed duplicate 'Chargement...' key since it was defined earlier
    'Réessayer': 'Réessayer',
    'Fermer': 'Fermer',
    'Ouvrir': 'Ouvrir',
    'Télécharger': 'Télécharger',
    'Partager': 'Partager',
    'Copier': 'Copier',
    'Coller': 'Coller',
    'Sélectionner': 'Sélectionner',
    'Tout sélectionner': 'Tout sélectionner',
    'Aucune sélection': 'Aucune sélection',
    'Valider': 'Valider',
    'Confirmer': 'Confirmer',
    'Ignorer': 'Ignorer',
    'Passer': 'Passer',
    'Précédent': 'Précédent',
    'Suivant': 'Suivant',
    'Terminer': 'Terminer',
    'Commencer': 'Commencer',
    'Arrêter': 'Arrêter',
    'Pause': 'Pause',
    'Reprendre': 'Reprendre',
    'Rejouer': 'Rejouer',
    'Nouveau': 'Nouveau',
    'Récent': 'Récent',
    'Ancien': 'Ancien',
    'Favoris': 'Favoris',
    'Ajouté aux favoris': 'Ajouté aux favoris',
    'Retiré des favoris': 'Retiré des favoris',
    'Historique': 'Historique',
    'Vider l\'historique': 'Vider l\'historique',

    // Navigation drawer
    'Offres d\'emploi': 'Offres d\'emploi',
    'Tableau de bord': 'Tableau de bord',
    'Espace Intérimaire': 'Espace Intérimaire',
    'Mes entretiens': 'Mes entretiens',
    'Recommandations IA': 'Recommandations IA',
    'Évaluations': 'Évaluations',
    'Dossier RH': 'Dossier RH',
    'Dossier IPM': 'Dossier IPM',
    'Messages': 'Messages',
    'Welcome': 'Bienvenue',

    // Authentification
    'Nom complet': 'Nom complet',
    'Adresse email': 'Adresse email',
    'Mot de passe': 'Mot de passe',
    'Confirmer le mot de passe': 'Confirmer le mot de passe',
    'Créer mon compte': 'Créer mon compte',
    'Candidat': 'Candidat',
    'Intérimaire': 'Intérimaire',
    'Les mots de passe correspondent': 'Les mots de passe correspondent',
    'Les mots de passe ne correspondent pas': 'Les mots de passe ne correspondent pas',
    'Très faible': 'Très faible',
    'Faible': 'Faible',
    'Moyen': 'Moyen',
    'Fort': 'Fort',
    'Très fort': 'Très fort',
  },
  en: {
    // General
    'Accueil': 'Home',
    'Paramètres': 'Settings',
    'Déconnexion': 'Logout',
    'Annuler': 'Cancel',
    'Sauvegarder': 'Save',
    'Erreur': 'Error',
    'Succès': 'Success',
    'Chargement...': 'Loading...',
    'Non renseigné': 'Not specified',
    'Voir tout': 'See all',

    // Settings
    'Préférences': 'Preferences',
    'Langue': 'Language',
    'Mode sombre': 'Dark Mode',
    'Activer le thème sombre': 'Enable dark theme',
    'Synchronisation auto': 'Auto Sync',
    'Synchroniser automatiquement les données': 'Automatically sync data',
    'Notifications': 'Notifications',
    'Notifications Push': 'Push Notifications',
    'Recevoir des notifications en temps réel': 'Receive real-time notifications',
    'Notifications par email': 'Email Notifications',
    'Recevoir des résumés par email': 'Receive email summaries',
    'Envoyer notification test': 'Send test notification',
    'Envoyer une notification pour tester': 'Send a test notification',
    'Sécurité': 'Security',
    'Authentification biométrique': 'Biometric Authentication',
    'Utiliser Face ID / Touch ID': 'Use Face ID / Touch ID',
    'Changer le mot de passe': 'Change password',
    'Modifier votre mot de passe': 'Modify your password',
    'Sessions actives': 'Active Sessions',
    'Gérer vos sessions connectées': 'Manage your connected sessions',
    'Compte': 'Account',
    'Informations personnelles': 'Personal Information',
    'Modifier votre profil': 'Edit your profile',
    'Confidentialité': 'Privacy',
    'Paramètres de confidentialité': 'Privacy settings',
    'Exporter mes données': 'Export my data',
    'Télécharger vos données': 'Download your data',
    'Support': 'Support',
    'Centre d\'aide': 'Help Center',
    'FAQ et guides d\'utilisation': 'FAQ and user guides',
    'Nous contacter': 'Contact Us',
    'Obtenir de l\'aide': 'Get help',
    'À propos': 'About',
    'Informations sur l\'application': 'App information',
    'Se déconnecter': 'Log Out',
    'Déconnexion...': 'Logging out...',
    'Confirmation': 'Confirmation',
    'Êtes-vous sûr de vouloir vous déconnecter ?': 'Are you sure you want to log out?',

    // Applications
    'Mes Candidatures': 'My Applications',
    'Toutes mes candidatures': 'All my applications',
    'En attente': 'Pending',
    'Acceptée': 'Accepted',
    'Refusée': 'Rejected',
    'Aucune candidature': 'No applications',
    'Vos candidatures apparaîtront ici': 'Your applications will appear here',
    'Chargement de vos candidatures...': 'Loading your applications...',
    'Impossible de charger vos candidatures.': 'Unable to load your applications.',
    'Retour': 'Back',
    'Retour aux candidatures': 'Back to applications',
    'Candidature introuvable': 'Application not found',
    'Cette candidature n\'existe plus ou n\'est pas accessible.': 'This application does not exist or is no longer accessible.',
    'Postulé le:': 'Applied on:',
    'Détails Candidature': 'Application Details',
    'Statut de la candidature': 'Application status',
    'Offre d\'emploi': 'Job Offer',
    'Lieu': 'Location',
    'Contrat': 'Contract',
    'Salaire': 'Salary',
    'Expérience': 'Experience',
    'Niveau': 'Level',
    'Domaine': 'Domain',
    'Lettre de motivation': 'Cover Letter',
    'Non spécifié': 'Not specified',
    'Non disponible': 'Not available',
    'N/A': 'N/A',
    'an(s)': 'year(s)',

    // News
    'Actualités': 'News',
    'Toutes les Actualités': 'All News',
    'Dernières Actualités': 'Latest News',
    'Chargement des actualités...': 'Loading news...',
    'Impossible de charger les actualités.': 'Unable to load news.',
    'Aucune actualité disponible pour le moment.': 'No news available at the moment.',
    'Publié le:': 'Published on:',
    'Vues:': 'Views:',
    'Catégorie:': 'Category:',
    'Description non disponible.': 'Description not available.',
    'Détails Actualité': 'News Details',

    // CV & Candidate Profile
    'Mon Profil': 'My Profile',
    'Mon CV & Candidat': 'My CV & Candidate',
    'Mes informations personnelles': 'My personal information',
    'Nom complet': 'Full name',
    'Email': 'Email',
    'Téléphone': 'Phone',
    'Nom': 'Name',
    'Modifier ces informations': 'Edit this information',
    'Nom complet CV': 'CV Full Name',
    'Email CV': 'CV Email',
    'Téléphone CV': 'CV Phone',
    'Résumé': 'Summary',
    'Résumé professionnel': 'Professional Summary',
    'Décrivez votre profil professionnel...': 'Describe your professional profile...',
    'Compétences': 'Skills',
    'Ajouter une compétence': 'Add a skill',
    'Expérience Professionnelle': 'Professional Experience',
    'Poste': 'Position',
    'Entreprise': 'Company',
    'Période': 'Period',
    'Lieu de travail': 'Work location',
    'Description': 'Description',
    'Formation': 'Education',
    'Nom de l\'établissement/diplôme': 'Institution/Degree Name',
    'Supprimer': 'Delete',
    'Ajouter une expérience': 'Add experience',
    'Ajouter une formation': 'Add education',
    'Télécharger/Mettre à jour le CV': 'Upload/Update CV',
    'Mes informations de CV': 'My CV Information',
    'Chargement des données...': 'Loading data...',
    'Aucune donnée CV': 'No CV data',
    'Saisissez manuellement vos informations ou téléchargez un CV.': 'Enter your information manually or upload a CV.',
    'Modifier les données du CV': 'Edit CV data',
    'Saisir les données du CV': 'Enter CV data',
    'Exporter le CV (PDF)': 'Export CV (PDF)',
    'Exportation...': 'Exporting...',
    'Impossible d\'exporter le CV.': 'Unable to export CV.',
    'Aucune donnée de CV à exporter.': 'No CV data to export.',
    'Titre de profil': 'Profile Title',
    'Disponibilité': 'Availability',
    'Statut': 'Status',
    'En Écoute': 'Available',
    'Indisponible': 'Unavailable',
    'Pas de profil candidat': 'No candidate profile',
    'Créez votre profil candidat pour postuler à des offres.': 'Create your candidate profile to apply for offers.',
    'Créer mon profil candidat': 'Create my candidate profile',
    'Statut (1: En Écoute, 0: Indisponible)': 'Status (1: Available, 0: Unavailable)',

    // Authentication and security
    'Configurer l\'authentification biométrique': 'Configure biometric authentication',
    'Souhaitez-vous configurer l\'authentification biométrique avec ces identifiants ?': 'Would you like to configure biometric authentication with these credentials?',
    'Authentification biométrique configurée avec succès !': 'Biometric authentication configured successfully!',
    'Échec de la configuration de l\'authentification biométrique.': 'Failed to configure biometric authentication.',
    'Erreur lors de la configuration.': 'Error during configuration.',
    'Connectez-vous d\'abord avec votre email et mot de passe pour activer la connexion biométrique.': 'Please log in first with your email and password to enable biometric login.',
    'Saisissez vos identifiants puis appuyez sur ce bouton pour configurer l\'authentification biométrique.': 'Enter your credentials then press this button to configure biometric authentication.',
    'Configurez l\'authentification biométrique en appuyant sur "Configurer".': 'Configure biometric authentication by pressing "Configure".',

    // Alerts and error messages
    'Veuillez saisir le code OTP et assurez-vous que l\'email est valide.': 'Please enter the OTP code and make sure the email is valid.',
    'Email manquant pour le renvoi d\'OTP.': 'Email missing for OTP resend.',
    'Lien invalide': 'Invalid Link',
    'Le lien de réinitialisation est invalide. Veuillez demander un nouveau lien.': 'The reset link is invalid. Please request a new link.',
    'Mot de passe réinitialisé': 'Password Reset',
    'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter.': 'Your password has been reset successfully. You can now log in.',
    'Une erreur s\'est produite. Redirection vers la connexion...': 'An error occurred. Redirecting to login...',

    // Temporary spaces and HR
    'Mon Dossier RH': 'My HR File',
    'Prestations IPM': 'IPM Services',
    'Structures de soins': 'Healthcare Facilities',
    'Détails de la structure': 'Facility Details',
    'Rapports': 'Reports',
    'Graphiques détaillés': 'Detailed Charts',
    'Carte IPM': 'IPM Card',
    'Analytics': 'Analytics',
    'Entretiens vidéo': 'Video Interviews',
    'Entretien vidéo': 'Video Interview',
    'Mes Favoris': 'My Favorites',

    // Specific error messages
    'Veuillez sélectionner un contrat.': 'Please select a contract.',
    'Veuillez écrire votre message.': 'Please write your message.',
    'Votre demande d\'attestation a été envoyée avec succès.': 'Your certificate request has been sent successfully.',
    'Attestation téléchargée avec succès !': 'Certificate downloaded successfully!',
    'Échec du téléchargement de l\'attestation.': 'Failed to download certificate.',
    'Impossible de télécharger l\'attestation.': 'Unable to download certificate.',
    'Certificat téléchargé avec succès !': 'Certificate downloaded successfully!',
    'Échec du téléchargement du certificat.': 'Failed to download certificate.',
    'Impossible de télécharger le certificat.': 'Unable to download certificate.',

    // Geolocation
    'Géolocalisation indisponible': 'Geolocation Unavailable',
    'Pour une meilleure expérience, activez la géolocalisation pour trouver les structures les plus proches.': 'For a better experience, enable geolocation to find the nearest facilities.',
    'Impossible de charger les structures': 'Unable to load facilities',
    'Position indisponible': 'Position Unavailable',
    'Impossible de calculer l\'itinéraire sans votre position': 'Unable to calculate route without your position',

    // Cards and sensitive data
    'Impossible de charger les informations de la carte': 'Unable to load card information',
    'Carte verrouillée': 'Card Locked',
    'Vous devez d\'abord déverrouiller la carte pour voir les données sensibles.': 'You must first unlock the card to view sensitive data.',
    'Carte déverrouillée': 'Card Unlocked',
    'Votre carte IPM est maintenant accessible.': 'Your IPM card is now accessible.',
    'Votre carte IPM est maintenant sécurisée.': 'Your IPM card is now secured.',
    'Données masquées': 'Data Masked',
    'Les données sensibles ont été masquées.': 'Sensitive data has been masked.',

    // Reports and analytics
    'Information': 'Information',
    'Aucun rapport disponible pour le moment.': 'No reports available at the moment.',
    'Impossible de charger l\'historique des rapports. Vérifiez votre connexion.': 'Unable to load report history. Check your connection.',
    '✅ Rapport généré': '✅ Report Generated',
    'Votre rapport a été généré avec succès et est maintenant disponible dans l\'historique.': 'Your report has been generated successfully and is now available in history.',
    '⚠️ Erreur': '⚠️ Error',
    'Impossible de générer le rapport. Veuillez réessayer.': 'Unable to generate report. Please try again.',
    'Impossible de générer le rapport. Vérifiez votre connexion et réessayez.': 'Unable to generate report. Check your connection and try again.',
    '✅ Succès': '✅ Success',
    'Rapport téléchargé et ouvert avec succès !': 'Report downloaded and opened successfully!',
    'Rapport sauvegardé dans': 'Report saved in',
    'Impossible de télécharger le rapport. Veuillez réessayer.': 'Unable to download report. Please try again.',

    // Analytics and data
    'Impossible de charger certaines données d\'analyse. Veuillez réessayer.': 'Unable to load some analytics data. Please try again.',
    'OK': 'OK',

    // Buttons and actions
    'Plus tard': 'Later',
    'Configurer': 'Configure',
    'Compris': 'Got it',

    // Notifications
    'Notifications activées !': 'Notifications enabled!',
    'Appareil physique requis': 'Physical Device Required',
    'Les notifications Push ne fonctionnent que sur les appareils physiques ou les émulateurs configurés pour Google Play Services !': 'Push notifications only work on physical devices or emulators configured for Google Play Services!',
    'Permission refusée': 'Permission Denied',
    'Impossible d\'obtenir le push token pour la notification ! Vous pouvez l\'activer dans les paramètres de votre appareil.': 'Unable to get push token for notification! You can enable it in your device settings.',
    'Impossible d\'activer les notifications. ': 'Unable to enable notifications. ',
    'Veuillez réessayer.': 'Please try again.',
    'Notifications désactivées': 'Notifications Disabled',
    'Les notifications ont été désactivées.': 'Notifications have been disabled.',

    // Advanced biometric configuration
    'Configuration de l\'authentification biométrique': 'Biometric Authentication Setup',
    'Pour configurer l\'authentification biométrique, veuillez saisir vos identifiants actuels.': 'To configure biometric authentication, please enter your current credentials.',
    'Configuration biométrique': 'Biometric Setup',
    'Saisissez vos identifiants pour configurer l\'authentification biométrique': 'Enter your credentials to configure biometric authentication',
    'Votre email': 'Your email',
    'Votre mot de passe': 'Your password',
    'Mot de passe': 'Password',
    'Veuillez saisir votre email et mot de passe': 'Please enter your email and password',

    // States and statuses
    'Non disponible sur cet appareil': 'Not available on this device',
    'Configuré et prêt à utiliser': 'Configured and ready to use',
    'Activé - Credentials requis': 'Enabled - Credentials required',

    // Various missing texts
    'Actualiser': 'Refresh',
    'Rechercher': 'Search',
    'Filtrer': 'Filter',
    'Trier': 'Sort',
    'Tout effacer': 'Clear all',
    'Aucun résultat': 'No results',
// Remove duplicate 'Chargement...' key since it was defined earlier
    'Réessayer': 'Retry',
    'Fermer': 'Close',
    'Ouvrir': 'Open',
    'Télécharger': 'Download',
    'Partager': 'Share',
    'Copier': 'Copy',
    'Coller': 'Paste',
    'Sélectionner': 'Select',
    'Tout sélectionner': 'Select all',
    'Aucune sélection': 'No selection',
    'Valider': 'Validate',
    'Confirmer': 'Confirm',
    'Ignorer': 'Ignore',
    'Passer': 'Skip',
    'Précédent': 'Previous',
    'Suivant': 'Next',
    'Terminer': 'Finish',
    'Commencer': 'Start',
    'Arrêter': 'Stop',
    'Pause': 'Pause',
    'Reprendre': 'Resume',
    'Rejouer': 'Replay',
    'Nouveau': 'New',
    'Récent': 'Recent',
    'Ancien': 'Old',
    'Favoris': 'Favorites',
    'Ajouté aux favoris': 'Added to favorites',
    'Retiré des favoris': 'Removed from favorites',
    'Historique': 'History',
    'Vider l\'historique': 'Clear history',

    // Navigation drawer
    'Offres d\'emploi': 'Job Offers',
    'Tableau de bord': 'Dashboard',
    'Espace Intérimaire': 'Temp Space',
    'Mes entretiens': 'My Interviews',
    'Recommandations IA': 'AI Recommendations',
    'Évaluations': 'Assessments',
    'Dossier RH': 'HR File',
    'Dossier IPM': 'IPM File',
    'Messages': 'Messages',
    'Welcome': 'Welcome',

    // Authentication
    'Nom complet': 'Full name',
    'Adresse email': 'Email address',
    'Mot de passe': 'Password',
    'Confirmer le mot de passe': 'Confirm password',
    'Créer mon compte': 'Create my account',
    'Candidat': 'Candidate',
    'Intérimaire': 'Temp Worker',
    'Les mots de passe correspondent': 'Passwords match',
    'Les mots de passe ne correspondent pas': 'Passwords do not match',
    'Très faible': 'Very weak',
    'Faible': 'Weak',
    'Moyen': 'Medium',
    'Fort': 'Strong',
    'Très fort': 'Very strong',
  },
  ar: {
    // General (Arabic, RTL support might need more adjustments)
    'Accueil': 'الرئيسية',
    'Paramètres': 'الإعدادات',
    'Déconnexion': 'تسجيل الخروج',
    'Annuler': 'إلغاء',
    'Sauvegarder': 'حفظ',
    'Erreur': 'خطأ',
    'Succès': 'نجاح',
    'Chargement...': 'جاري التحميل...',
    'Non renseigné': 'غير محدد',
    'Voir tout': 'عرض الكل',

    // Settings
    'Préférences': 'التفضيلات',
    'Langue': 'اللغة',
    'Mode sombre': 'الوضع الداكن',
    'Activer le thème sombre': 'تفعيل الوضع الداكن',
    'Synchronisation auto': 'المزامنة التلقائية',
    'Synchroniser automatiquement les données': 'مزامنة البيانات تلقائيًا',
    'Notifications': 'الإشعارات',
    'Notifications Push': 'إشعارات الدفع',
    'Recevoir des notifications en temps réel': 'استلام الإشعارات في الوقت الفعلي',
    'Notifications par email': 'إشعارات البريد الإلكتروني',
    'Recevoir des résumés par email': 'استلام ملخصات عبر البريد الإلكتروني',
    'Envoyer notification test': 'إرسال إشعار تجريبي',
    'Envoyer une notification pour tester': 'إرسال إشعار لاختبار',
    'Sécurité': 'الأمان',
    'Authentification biométrique': 'المصادقة البيومترية',
    'Utiliser Face ID / Touch ID': 'استخدام Face ID / Touch ID',
    'Changer le mot de passe': 'تغيير كلمة المرور',
    'Modifier votre mot de passe': 'تعديل كلمة المرور الخاصة بك',
    'Sessions actives': 'الجلسات النشطة',
    'Gérer vos sessions connectées': 'إدارة جلساتك المتصلة',
    'Compte': 'الحساب',
    'Informations personnelles': 'المعلومات الشخصية',
    'Modifier votre profil': 'تعديل ملفك الشخصي',
    'Confidentialité': 'الخصوصية',
    'Paramètres de confidentialité': 'إعدادات الخصوصية',
    'Exporter mes données': 'تصدير بياناتي',
    'Télécharger vos données': 'تحميل بياناتك',
    'Support': 'الدعم',
    'Centre d\'aide': 'مركز المساعدة',
    'FAQ et guides d\'utilisation': 'الأسئلة الشائعة وأدلة المستخدم',
    'Nous contacter': 'اتصل بنا',
    'Obtenir de l\'aide': 'الحصول على المساعدة',
    'À propos': 'حول التطبيق',
    'Informations sur l\'application': 'معلومات عن التطبيق',
    'Se déconnecter': 'تسجيل الخروج',
    'Déconnexion...': 'جاري تسجيل الخروج...',
    'Confirmation': 'تأكيد',
    'Êtes-vous sûr de vouloir vous déconnecter ?': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',

    // Applications
    'Mes Candidatures': 'طلباتي',
    'Toutes mes candidatures': 'جميع طلباتي',
    'En attente': 'في الانتظار',
    'Acceptée': 'مقبولة',
    'Refusée': 'مرفوضة',
    'Aucune candidature': 'لا توجد طلبات',
    'Vos candidatures apparaîtront ici': 'ستظهر طلباتك هنا',
    'Chargement de vos candidatures...': 'جاري تحميل طلباتك...',
    'Impossible de charger vos candidatures.': 'لا يمكن تحميل طلباتك.',
    'Retour': 'رجوع',
    'Retour aux candidatures': 'العودة إلى الطلبات',
    'Candidature introuvable': 'لم يتم العثور على الطلب',
    'Cette candidature n\'existe plus ou n\'est pas accessible.': 'هذا الطلب لم يعد موجودًا أو غير متاح.',
    'Postulé le:': 'تم التقديم في:',
    'Détails Candidature': 'تفاصيل الطلب',
    'Statut de la candidature': 'حالة الطلب',
    'Offre d\'emploi': 'عرض عمل',
    'Lieu': 'الموقع',
    'Contrat': 'العقد',
    'Salaire': 'الراتب',
    'Expérience': 'الخبرة',
    'Niveau': 'المستوى',
    'Domaine': 'المجال',
    'Lettre de motivation': 'رسالة تغطية',
    'Non spécifié': 'غير محدد',
    'Non disponible': 'غير متوفر',
    'N/A': 'غير متاح',
    'an(s)': 'سنة/سنوات',

    // Actualités
    'Actualités': 'الأخبار',
    'Toutes les Actualités': 'جميع الأخبار',
    'Dernières Actualités': 'آخر الأخبار',
    'Chargement des actualités...': 'جاري تحميل الأخبار...',
    'Impossible de charger les actualités.': 'لا يمكن تحميل الأخبار.',
    'Aucune actualité disponible pour le moment.': 'لا توجد أخبار متاحة حاليا.',
    'Publié le:': 'نشر في:',
    'Vues:': 'المشاهدات:',
    'Catégorie:': 'الفئة:',
    'Description non disponible.': 'الوصف غير متاح.',
    'Détails Actualité': 'تفاصيل الخبر',

    // CV & Candidat Profile
    'Mon Profil': 'ملفي الشخصي',
    'Mon CV & Candidat': 'سيرتي الذاتية والمترشح',
    'Mes informations personnelles': 'معلوماتي الشخصية',
    'Nom complet': 'الاسم الكامل',
    'Email': 'البريد الإلكتروني',
    'Téléphone': 'الهاتف',
    'Nom': 'الاسم',
    'Modifier ces informations': 'تعديل هذه المعلومات',
    'Nom complet CV': 'الاسم الكامل في السيرة الذاتية',
    'Email CV': 'البريد الإلكتروني في السيرة الذاتية',
    'Téléphone CV': 'الهاتف في السيرة الذاتية',
    'Résumé': 'الملخص',
    'Résumé professionnel': 'الملخص المهني',
    'Décrivez votre profil professionnel...': 'صف ملفك المهني...',
    'Compétences': 'المهارات',
    'Ajouter une compétence': 'إضافة مهارة',
    'Expérience Professionnelle': 'الخبرة المهنية',
    'Poste': 'المنصب',
    'Entreprise': 'الشركة',
    'Période': 'الفترة',
    'Lieu de travail': 'مكان العمل',
    'Description': 'الوصف',
    'Formation': 'التعليم',
    'Nom de l\'établissement/diplôme': 'اسم المؤسسة/الشهادة',
    'Supprimer': 'حذف',
    'Ajouter une expérience': 'إضافة خبرة',
    'Ajouter une formation': 'إضافة تعليم',
    'Télécharger/Mettre à jour le CV': 'تحميل/تحديث السيرة الذاتية',
    'Mes informations de CV': 'معلومات سيرتي الذاتية',
    'Chargement des données...': 'جاري تحميل البيانات...',
    'Aucune donnée CV': 'لا توجد بيانات سيرة ذاتية',
    'Saisissez manuellement vos informations ou téléchargez un CV.': 'أدخل معلوماتك يدويًا أو قم بتحميل سيرة ذاتية.',
    'Modifier les données du CV': 'تعديل بيانات السيرة الذاتية',
    'Saisir les données du CV': 'إدخال بيانات السيرة الذاتية',
    'Exporter le CV (PDF)': 'تصدير السيرة الذاتية (PDF)',
    'Exportation...': 'جاري التصدير...',
    'Impossible d\'exporter le CV.': 'لا يمكن تصدير السيرة الذاتية.',
    'Aucune donnée de CV à exporter.': 'لا توجد بيانات سيرة ذاتية لتصديرها.',
    'Titre de profil': 'عنوان الملف الشخصي',
    'Disponibilité': 'التوفر',
    'Statut': 'الحالة',
    'En Écoute': 'متاح',
    'Indisponible': 'غير متاح',
    'Pas de profil candidat': 'لا يوجد ملف مرشح',
    'Créez votre profil candidat pour postuler à des offres.': 'أنشئ ملفك الشخصي كمرشح للتقدم للوظائف.',
    'Créer mon profil candidat': 'إنشاء ملفي الشخصي كمرشح',
    'Statut (1: En Écoute, 0: Indisponible)': 'الحالة (1: متاح، 0: غير متاح)',

    // المصادقة والأمان
    'Configurer l\'authentification biométrique': 'إعداد المصادقة البيومترية',
    'Souhaitez-vous configurer l\'authentification biométrique avec ces identifiants ?': 'هل تريد إعداد المصادقة البيومترية باستخدام هذه المعلومات؟',
    'Authentification biométrique configurée avec succès !': 'تم إعداد المصادقة البيومترية بنجاح!',
    'Échec de la configuration de l\'authentification biométrique.': 'فشل في إعداد المصادقة البيومترية.',
    'Erreur lors de la configuration.': 'خطأ أثناء الإعداد.',
    'Connectez-vous d\'abord avec votre email et mot de passe pour activer la connexion biométrique.': 'يرجى تسجيل الدخول أولاً بالبريد الإلكتروني وكلمة المرور لتفعيل تسجيل الدخول البيومتري.',
    'Saisissez vos identifiants puis appuyez sur ce bouton pour configurer l\'authentification biométrique.': 'أدخل بياناتك ثم اضغط على هذا الزر لإعداد المصادقة البيومترية.',
    'Configurez l\'authentification biométrique en appuyant sur "Configurer".': 'قم بإعداد المصادقة البيومترية بالضغط على "إعداد".',

    // التنبيهات ورسائل الخطأ
    'Veuillez saisir le code OTP et assurez-vous que l\'email est valide.': 'يرجى إدخال رمز OTP والتأكد من صحة البريد الإلكتروني.',
    'Email manquant pour le renvoi d\'OTP.': 'البريد الإلكتروني مفقود لإعادة إرسال OTP.',
    'Lien invalide': 'رابط غير صالح',
    'Le lien de réinitialisation est invalide. Veuillez demander un nouveau lien.': 'رابط إعادة التعيين غير صالح. يرجى طلب رابط جديد.',
    'Mot de passe réinitialisé': 'تم إعادة تعيين كلمة المرور',
    'Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter.': 'تم إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول.',
    'Une erreur s\'est produite. Redirection vers la connexion...': 'حدث خطأ. جاري إعادة التوجيه إلى تسجيل الدخول...',

    // المساحات المؤقتة والموارد البشرية
    'Mon Dossier RH': 'ملف الموارد البشرية',
    'Prestations IPM': 'خدمات IPM',
    'Structures de soins': 'المرافق الصحية',
    'Détails de la structure': 'تفاصيل المرفق',
    'Rapports': 'التقارير',
    'Graphiques détaillés': 'الرسوم البيانية التفصيلية',
    'Carte IPM': 'بطاقة IPM',
    'Analytics': 'التحليلات',
    'Entretiens vidéo': 'المقابلات المرئية',
    'Entretien vidéo': 'مقابلة مرئية',
    'Mes Favoris': 'مفضلاتي',

    // رسائل خطأ محددة
    'Veuillez sélectionner un contrat.': 'يرجى اختيار عقد.',
    'Veuillez écrire votre message.': 'يرجى كتابة رسالتك.',
    'Votre demande d\'attestation a été envoyée avec succès.': 'تم إرسال طلب الشهادة بنجاح.',
    'Attestation téléchargée avec succès !': 'تم تحميل الشهادة بنجاح!',
    'Échec du téléchargement de l\'attestation.': 'فشل في تحميل الشهادة.',
    'Impossible de télécharger l\'attestation.': 'لا يمكن تحميل الشهادة.',
    'Certificat téléchargé avec succès !': 'تم تحميل الشهادة بنجاح!',
    'Échec du téléchargement du certificat.': 'فشل في تحميل الشهادة.',
    'Impossible de télécharger le certificat.': 'لا يمكن تحميل الشهادة.',

    // الموقع الجغرافي
    'Géolocalisation indisponible': 'الموقع الجغرافي غير متاح',
    'Pour une meilleure expérience, activez la géolocalisation pour trouver les structures les plus proches.': 'للحصول على تجربة أفضل، فعّل الموقع الجغرافي للعثور على أقرب المرافق.',
    'Impossible de charger les structures': 'لا يمكن تحميل المرافق',
    'Position indisponible': 'الموقع غير متاح',
    'Impossible de calculer l\'itinéraire sans votre position': 'لا يمكن حساب المسار بدون موقعك',

    // البطاقات والبيانات الحساسة
    'Impossible de charger les informations de la carte': 'لا يمكن تحميل معلومات البطاقة',
    'Carte verrouillée': 'البطاقة مقفلة',
    'Vous devez d\'abord déverrouiller la carte pour voir les données sensibles.': 'يجب عليك أولاً إلغاء قفل البطاقة لعرض البيانات الحساسة.',
    'Carte déverrouillée': 'تم إلغاء قفل البطاقة',
    'Votre carte IPM est maintenant accessible.': 'بطاقة IPM الخاصة بك متاحة الآن.',
    'Votre carte IPM est maintenant sécurisée.': 'بطاقة IPM الخاصة بك آمنة الآن.',
    'Données masquées': 'البيانات مخفية',
    'Les données sensibles ont été masquées.': 'تم إخفاء البيانات الحساسة.',

    // التقارير والتحليلات
    'Information': 'معلومات',
    'Aucun rapport disponible pour le moment.': 'لا توجد تقارير متاحة في الوقت الحالي.',
    'Impossible de charger l\'historique des rapports. Vérifiez votre connexion.': 'لا يمكن تحميل تاريخ التقارير. تحقق من اتصالك.',
    '✅ Rapport généré': '✅ تم إنشاء التقرير',
    'Votre rapport a été généré avec succès et est maintenant disponible dans l\'historique.': 'تم إنشاء تقريرك بنجاح وهو متاح الآن في التاريخ.',
    '⚠️ Erreur': '⚠️ خطأ',
    'Impossible de générer le rapport. Veuillez réessayer.': 'لا يمكن إنشاء التقرير. يرجى المحاولة مرة أخرى.',
    'Impossible de générer le rapport. Vérifiez votre connexion et réessayez.': 'لا يمكن إنشاء التقرير. تحقق من اتصالك وحاول مرة أخرى.',
    '✅ Succès': '✅ نجح',
    'Rapport téléchargé et ouvert avec succès !': 'تم تحميل وفتح التقرير بنجاح!',
    'Rapport sauvegardé dans': 'تم حفظ التقرير في',
    'Impossible de télécharger le rapport. Veuillez réessayer.': 'لا يمكن تحميل التقرير. يرجى المحاولة مرة أخرى.',

    // التحليلات والبيانات
    'Impossible de charger certaines données d\'analyse. Veuillez réessayer.': 'لا يمكن تحميل بعض بيانات التحليل. يرجى المحاولة مرة أخرى.',
    'OK': 'موافق',

    // الأزرار والإجراءات
    'Plus tard': 'لاحقاً',
    'Configurer': 'إعداد',
    'Compris': 'فهمت',

    // الإشعارات
    'Notifications activées !': 'تم تفعيل الإشعارات!',
    'Appareil physique requis': 'مطلوب جهاز فعلي',
    'Les notifications Push ne fonctionnent que sur les appareils physiques ou les émulateurs configurés pour Google Play Services !': 'الإشعارات الفورية تعمل فقط على الأجهزة الفعلية أو المحاكيات المكونة لخدمات Google Play!',
    'Permission refusée': 'تم رفض الإذن',
    'Impossible d\'obtenir le push token pour la notification ! Vous pouvez l\'activer dans les paramètres de votre appareil.': 'لا يمكن الحصول على رمز الدفع للإشعار! يمكنك تفعيله في إعدادات جهازك.',
    'Impossible d\'activer les notifications. ': 'لا يمكن تفعيل الإشعارات. ',
    'Veuillez réessayer.': 'يرجى المحاولة مرة أخرى.',
    'Notifications désactivées': 'تم تعطيل الإشعارات',
    'Les notifications ont été désactivées.': 'تم تعطيل الإشعارات.',

    // إعداد المصادقة البيومترية المتقدم
    'Configuration de l\'authentification biométrique': 'إعداد المصادقة البيومترية',
    'Pour configurer l\'authentification biométrique, veuillez saisir vos identifiants actuels.': 'لإعداد المصادقة البيومترية، يرجى إدخال بيانات اعتمادك الحالية.',
    'Configuration biométrique': 'الإعداد البيومتري',
    'Saisissez vos identifiants pour configurer l\'authentification biométrique': 'أدخل بياناتك لإعداد المصادقة البيومترية',
    'Votre email': 'بريدك الإلكتروني',
    'Votre mot de passe': 'كلمة مرورك',
    'Mot de passe': 'كلمة المرور',
    'Veuillez saisir votre email et mot de passe': 'يرجى إدخال بريدك الإلكتروني وكلمة المرور',

    // الحالات والأوضاع
    'Non disponible sur cet appareil': 'غير متاح على هذا الجهاز',
    'Configuré et prêt à utiliser': 'تم التكوين وجاهز للاستخدام',
    'Activé - Credentials requis': 'مفعل - مطلوب بيانات الاعتماد',

    // نصوص متنوعة مفقودة
    'Actualiser': 'تحديث',
    'Rechercher': 'البحث',
    'Filtrer': 'تصفية',
    'Trier': 'ترتيب',
    'Tout effacer': 'مسح الكل',
    'Aucun résultat': 'لا توجد نتائج',
    'Loading...': 'جاري التحميل...',
    'Réessayer': 'إعادة المحاولة',
    'Fermer': 'إغلاق',
    'Ouvrir': 'فتح',
    'Télécharger': 'تحميل',
    'Partager': 'مشاركة',
    'Copier': 'نسخ',
    'Coller': 'لصق',
    'Sélectionner': 'تحديد',
    'Tout sélectionner': 'تحديد الكل',
    'Aucune sélection': 'لا يوجد تحديد',
    'Valider': 'تأكيد',
    'Confirmer': 'تأكيد',
    'Ignorer': 'تجاهل',
    'Passer': 'تخطي',
    'Précédent': 'السابق',
    'Suivant': 'التالي',
    'Terminer': 'إنهاء',
    'Commencer': 'بدء',
    'Arrêter': 'إيقاف',
    'Pause': 'إيقاف مؤقت',
    'Reprendre': 'استئناف',
    'Rejouer': 'إعادة تشغيل',
    'Nouveau': 'جديد',
    'Récent': 'حديث',
    'Ancien': 'قديم',
    'Favoris': 'المفضلة',
    'Ajouté aux favoris': 'أضيف للمفضلة',
    'Retiré des favoris': 'أزيل من المفضلة',
    'Historique': 'التاريخ',
    'Vider l\'historique': 'مسح التاريخ',

    // Navigation drawer
    'Offres d\'emploi': 'عروض العمل',
    'Tableau de bord': 'لوحة المعلومات',
    'Espace Intérimaire': 'مساحة العمل المؤقت',
    'Mes entretiens': 'مقابلاتي',
    'Recommandations IA': 'توصيات الذكاء الاصطناعي',
    'Évaluations': 'التقييمات',
    'Dossier RH': 'ملف الموارد البشرية',
    'Dossier IPM': 'ملف IPM',
    'Messages': 'الرسائل',
    'Welcome': 'مرحباً',

    // المصادقة
    'Nom complet': 'الاسم الكامل',
    'Adresse email': 'عنوان البريد الإلكتروني',
    'Mot de passe': 'كلمة المرور',
    'Confirmer le mot de passe': 'تأكيد كلمة المرور',
    'Créer mon compte': 'إنشاء حسابي',
    'Candidat': 'مرشح',
    'Intérimaire': 'عامل مؤقت',
    'Les mots de passe correspondent': 'كلمات المرور متطابقة',
    'Les mots de passe ne correspondent pas': 'كلمات المرور غير متطابقة',
    'Très faible': 'ضعيف جداً',
    'Faible': 'ضعيف',
    'Moyen': 'متوسط',
    'Fort': 'قوي',
    'Très fort': 'قوي جداً',
  },
};

// Interface pour le contexte de langue
interface LanguageContextType {
  language: string; // 'fr', 'en', 'ar'
  setLanguage: (lang: string) => void;
  t: (key: string) => string; // Fonction de traduction
}

// Création du contexte avec des valeurs par défaut
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Clé pour AsyncStorage
const ASYNC_STORAGE_KEY_LANG = '@app_language_mode';

// Fournisseur de langue
interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Langue par défaut : français
  const [language, setLanguageState] = useState('fr');

  // Charger la langue préférée de l'utilisateur depuis AsyncStorage
  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const storedLang = await AsyncStorage.getItem(ASYNC_STORAGE_KEY_LANG);
        if (storedLang && ['fr', 'en', 'ar'].includes(storedLang)) {
          setLanguageState(storedLang);
        } else {
          // Définir la langue par défaut du système si aucune préférence n'est stockée et que la détection système est possible
          // Pour l'instant, on reste sur 'fr' si rien n'est stocké
          setLanguageState('fr'); 
        }
      } catch (e) {
        console.error("Failed to load language from AsyncStorage", e);
      }
    };
    loadLanguage();
  }, []);

  // Fonction pour changer la langue et la sauvegarder
  const setLanguage = useCallback(async (lang: string) => {
    if (['fr', 'en', 'ar'].includes(lang)) {
      setLanguageState(lang);
      try {
        await AsyncStorage.setItem(ASYNC_STORAGE_KEY_LANG, lang);
      } catch (e) {
        console.error("Failed to save language to AsyncStorage", e);
      }
    } else {
      console.warn("Langue non supportée:", lang);
    }
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language as keyof typeof translations][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook personnalisé pour utiliser la langue
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
